config/routes.php
<?php
/**
 * Routes configuration
 *
 * In this file, you set up routes to your controllers and their actions.
 * Routes are very important mechanism that allows you to freely connect
 * different URLs to chosen controllers and their actions (functions).
 *
 * CakePHP(tm) : Rapid Development Framework (http://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)
 * @link          http://cakephp.org CakePHP(tm) Project
 * @license       http://www.opensource.org/licenses/mit-license.php MIT License
 */

use Cake\Core\Plugin;
use Cake\Routing\RouteBuilder;
use Cake\Routing\Router;
use Cake\Routing\Route\DashedRoute;

/**
 * The default class to use for all routes
 *
 * The following route classes are supplied with CakePHP and are appropriate
 * to set as the default:
 *
 * - Route
 * - InflectedRoute
 * - DashedRoute
 *
 * If no call is made to `Router::defaultRouteClass()`, the class used is
 * `Route` (`Cake\Routing\Route\Route`)
 *
 * Note that `Route` does not do any inflections on URLs which will result in
 * inconsistently cased URLs when used with `:plugin`, `:controller` and
 * `:action` markers.
 *
 */
Router::defaultRouteClass(DashedRoute::class);

Router::scope('/', function (RouteBuilder $routes) {
    /**
     * Here, we are connecting '/' (base path) to a controller called 'Pages',
     * its action called 'display', and we pass a param to select the view file
     * to use (in this case, src/Template/Pages/home.ctp)...
     */
    $routes->connect('/', ['controller' => 'users', 'action' => 'login']);

    /**
     * ...and connect the rest of 'Pages' controller's URLs.
     */
    $routes->connect('/pages/*', ['controller' => 'Pages', 'action' => 'display']);

    /**
     * Connect catchall routes for all controllers.
     *
     * Using the argument `DashedRoute`, the `fallbacks` method is a shortcut for
     *    `$routes->connect('/:controller', ['action' => 'index'], ['routeClass' => 'DashedRoute']);`
     *    `$routes->connect('/:controller/:action/*', [], ['routeClass' => 'DashedRoute']);`
     *
     * Any route class can be used with this method, such as:
     * - DashedRoute
     * - InflectedRoute
     * - Route
     * - Or your own route class
     *
     * You can remove these routes once you've connected the
     * routes you want in your application.
     */
    $routes->fallbacks(DashedRoute::class);
});

/**
 * Load all plugin routes.  See the Plugin documentation on
 * how to customize the loading of plugin routes.
 */
Plugin::routes();

src/Model/Entity/Contacto.php
<?php
namespace App\Model\Entity;

use Cake\ORM\Entity;

/**
 * Contacto Entity
 *
 * @property int $id
 * @property int $persona_id
 * @property string $movil
 * @property string $casa
 * @property string $twitter
 * @property string $facebook
 * @property string $email
 * @property \Cake\I18n\Time $created
 * @property \Cake\I18n\Time $modified
 *
 * @property \App\Model\Entity\Persona[] $personas
 */
class Contacto extends Entity
{

    /**
     * Fields that can be mass assigned using newEntity() or patchEntity().
     *
     * Note that when '*' is set to true, this allows all unspecified fields to
     * be mass assigned. For security purposes, it is advised to set '*' to false
     * (or remove it), and explicitly make individual fields accessible as needed.
     *
     * @var array
     */
    protected $_accessible = [
        '*' => true,
        'id' => false
    ];
}

src/Model/Entity/Persona.php
<?php
namespace App\Model\Entity;

use Cake\ORM\Entity;

/**
 * Persona Entity
 *
 * @property int $id
 * @property string $nacionalidad
 * @property int $cedula
 * @property string $nombre
 * @property string $nombre_1
 * @property string $apellido
 * @property string $apellido_1
 * @property bool $sexo
 * @property \Cake\I18n\Time $nacimiento
 * @property int $estado_id
 * @property int $municipio_id
 * @property int $parroquia_id
 * @property int $contacto_id
 * @property int $representante_id
 * @property int $user_id
 * @property \Cake\I18n\Time $created
 * @property \Cake\I18n\Time $modified
 *
 * @property \App\Model\Entity\Estado $estado
 * @property \App\Model\Entity\Municipio $municipio
 * @property \App\Model\Entity\Parroquia $parroquia
 * @property \App\Model\Entity\Contacto[] $contactos
 * @property \App\Model\Entity\User $user
 * @property \App\Model\Entity\Fotospersona[] $fotospersonas
 */
class Persona extends Entity
{

    /**
     * Fields that can be mass assigned using newEntity() or patchEntity().
     *
     * Note that when '*' is set to true, this allows all unspecified fields to
     * be mass assigned. For security purposes, it is advised to set '*' to false
     * (or remove it), and explicitly make individual fields accessible as needed.
     *
     * @var array
     */
    protected $_accessible = [
        '*' => true,
        'id' => false
    ];

    protected function _getNombreConCedula()
    {
        return 'C. I. '. $this->_properties['cedula'].' - '.$this->_properties['nombre']. ' ' .$this->_properties['apellido'];
    }

    protected function _getNombreSimple()
    {
        return $this->_properties['nombre'] . ' ' .$this->_properties['apellido'];
    }

    protected function _getNombreCompleto()
    {
        return $this->_properties['nombre'] . ' ' .$this->_properties['nombre_1']. ' ' .$this->_properties['apellido']. ' ' .$this->_properties['apellido_1'];
    }
    protected function _getLugarNacimiento()
    {
        return $this->_properties['parroquia']['parroquia'] . ', Municipio ' .$this->_properties['municipio']['municipio']. ', Edo. ' .$this->_properties['estado']['estado'];
    }
}

src/Model/Table/ContactosTable.php
<?php
namespace App\Model\Table;

use Cake\ORM\Query;
use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\Validation\Validator;

/**
 * Contactos Model
 *
 * @property \Cake\ORM\Association\BelongsTo $Personas
 * @property \Cake\ORM\Association\HasMany $Personas
 *
 * @method \App\Model\Entity\Contacto get($primaryKey, $options = [])
 * @method \App\Model\Entity\Contacto newEntity($data = null, array $options = [])
 * @method \App\Model\Entity\Contacto[] newEntities(array $data, array $options = [])
 * @method \App\Model\Entity\Contacto|bool save(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \App\Model\Entity\Contacto patchEntity(\Cake\Datasource\EntityInterface $entity, array $data, array $options = [])
 * @method \App\Model\Entity\Contacto[] patchEntities($entities, array $data, array $options = [])
 * @method \App\Model\Entity\Contacto findOrCreate($search, callable $callback = null)
 *
 * @mixin \Cake\ORM\Behavior\TimestampBehavior
 */
class ContactosTable extends Table
{

    /**
     * Initialize method
     *
     * @param array $config The configuration for the Table.
     * @return void
     */
    public function initialize(array $config)
    {
        parent::initialize($config);

        $this->table('contactos');
        $this->displayField('id');
        $this->primaryKey('id');

        $this->addBehavior('Timestamp');

        $this->belongsTo('Personas', [
            'foreignKey' => 'persona_id',
            'joinType' => 'INNER'
        ]);
    }

    /**
     * Default validation rules.
     *
     * @param \Cake\Validation\Validator $validator Validator instance.
     * @return \Cake\Validation\Validator
     */
    public function validationDefault(Validator $validator)
    {
        $validator
            ->integer('id')
            ->allowEmpty('id', 'create');

        $validator
            ->requirePresence('movil', 'create')
            ->notEmpty('movil');

        $validator
            ->requirePresence('casa', 'create')
            ->notEmpty('casa');

        $validator
            ->allowEmpty('twitter');

        $validator
            ->allowEmpty('facebook');

        return $validator;
    }

    /**
     * Returns a rules checker object that will be used for validating
     * application integrity.
     *
     * @param \Cake\ORM\RulesChecker $rules The rules object to be modified.
     * @return \Cake\ORM\RulesChecker
     */
    public function buildRules(RulesChecker $rules)
    {
        $rules->add($rules->isUnique(['email']));
        $rules->add($rules->existsIn(['persona_id'], 'Personas'));

        return $rules;
    }
}

src/Controller/ContactosController.php
<?php
namespace App\Controller;

use App\Controller\AppController;

/**
 * Contactos Controller
 *
 * @property \App\Model\Table\ContactosTable $Contactos
 */
class ContactosController extends AppController
{

    /**
     * Index method
     *
     * @return \Cake\Network\Response|null
     */

     public function info()
     {
         $user=$this->Auth->user();
         $contactos = $this->Contactos->find('all')->where(['persona_id'=>$user->persona->id]);
         $this->set(compact('contactos'));
         $this->set('_serialize', ['contactos']);
     }
    public function index()
    {
        $contactos = $this->paginate($this->Contactos);

        $this->set(compact('contactos'));
        $this->set('_serialize', ['contactos']);
    }

    /**
     * View method
     *
     * @param string|null $id Contacto id.
     * @return \Cake\Network\Response|null
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function view($id = null)
    {
        return $this->redirect(['action' => 'info',$id]);
    }

    /**
     * Add method
     *
     * @return \Cake\Network\Response|void Redirects on successful add, renders view otherwise.
     */
    public function add($id = null)
    {
        $user=$this->Auth->user();
        $id=$id?$id:$user->persona->id;
        $contacto = $this->Contactos->newEntity();
        if ($this->request->is('post')) {
            $contacto = $this->Contactos->patchEntity($contacto, $this->request->data);
            $contacto->persona_id=$id;
            if ($this->Contactos->save($contacto)) {
                $this->Flash->success(__('Datos guardados.'));

                return $this->redirect(['action' => 'info',$user->persona->id]);
            } else {
                $this->Flash->error(__('Ha ocurrido un error.'));
            }
        }
        $this->set(compact('contacto'));
        $this->set('_serialize', ['contacto']);
    }

    /**
     * Edit method
     *
     * @param string|null $id Contacto id.
     * @return \Cake\Network\Response|void Redirects on successful edit, renders view otherwise.
     * @throws \Cake\Network\Exception\NotFoundException When record not found.
     */
    public function edit($id = null)
    {
        $contacto = $this->Contactos->get($id, [
            'contain' => ['Personas']
        ]);
        if ($this->request->is(['patch', 'post', 'put'])) {
            $contacto = $this->Contactos->patchEntity($contacto, $this->request->data);
            if ($this->Contactos->save($contacto)) {
                $this->Flash->success(__('Datos actualizados.'));

                return $this->redirect(['action' => 'info',$contacto->persona_id]);
            } else {
                $this->Flash->error(__('Ha ocurrido un error.'));
            }
        }
        $this->set(compact('contacto'));
        $this->set('_serialize', ['contacto']);
    }

    /**
     * Delete method
     *
     * @param string|null $id Contacto id.
     * @return \Cake\Network\Response|null Redirects to index.
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function delete($id = null)
    {
        $this->request->allowMethod(['post', 'delete']);
        $contacto = $this->Contactos->get($id);
        if ($this->Contactos->delete($contacto)) {
            $this->Flash->success(__('The contacto has been deleted.'));
        } else {
            $this->Flash->error(__('The contacto could not be deleted. Please, try again.'));
        }

        return $this->redirect(['action' => 'info']);
    }
}

src/Template/Contactos/add.ctp
<?php $loguser = $this->request->session()->read('Auth.User'); ?>
<div class="col-md-10 col-md-offset-1 col-sm-12">
    <?= $this->Form->create($contacto) ?>
    <fieldset>
        <legend><?= $loguser->persona->nombre_simple.__(': Agregando datos de contacto') ?></legend>
        <div class="col-md-6 col-sm-12">
            <?php
                //echo $this->Form->hidden('persona_id');
                echo $this->Form->input('movil',['class'=>'form-control','label'=>'Telf. Móvil','placeholder'=>'04243334567']);
                echo $this->Form->input('casa',['class'=>'form-control','label'=>'Telf. Fijo','placeholder'=>'02468767878']);
            ?>
        </div>
        <div class="col-md-6 col-sm-12">
            <?php
                echo $this->Form->input('twitter',['class'=>'form-control','label'=>'Twitter','placeholder'=>'@usuario']);
                echo $this->Form->input('facebook',['class'=>'form-control','label'=>'Facebook']);
            ?>
        </div>
    </fieldset>
    <?= $this->Form->button(__('Guardar'),['class'=>'btn btn-primary']) ?>
    <?= $this->Form->end() ?>
</div>

src/Template/Contactos/edit.ctp
<?php $loguser = $this->request->session()->read('Auth.User'); ?>
<div class="col-md-10 col-md-offset-1 col-sm-12">
    <?= $this->Form->create($contacto) ?>
    <fieldset>
        <legend><?= $loguser->persona->nombre_simple.__(': Actualizando datos de contacto') ?></legend>
        <div class="col-md-6 col-sm-12">
            <?php
                echo $this->Form->hidden('persona_id');
                echo $this->Form->input('movil',['class'=>'form-control','label'=>'Telf. Móvil','placeholder'=>'04243334567']);
                echo $this->Form->input('casa',['class'=>'form-control','label'=>'Telf. Fijo','placeholder'=>'02468767878']);
            ?>
        </div>
        <div class="col-md-6 col-sm-12">
            <?php
                echo $this->Form->input('twitter',['class'=>'form-control','label'=>'Twitter','placeholder'=>'@usuario']);
                echo $this->Form->input('facebook',['class'=>'form-control','label'=>'Facebook']);
            ?>
        </div>
    </fieldset>
    <?= $this->Form->button(__('Guardar'),['class'=>'btn btn-primary']) ?>
    <?= $this->Form->end() ?>
</div>

src/Template/Contactos/index.ctp
<nav class="large-3 medium-4 columns" id="actions-sidebar">
    <ul class="side-nav">
        <li class="heading"><?= __('Actions') ?></li>
        <li><?= $this->Html->link(__('New Contacto'), ['action' => 'add']) ?></li>
        <li><?= $this->Html->link(__('List Personas'), ['controller' => 'Personas', 'action' => 'index']) ?></li>
        <li><?= $this->Html->link(__('New Persona'), ['controller' => 'Personas', 'action' => 'add']) ?></li>
    </ul>
</nav>
<div class="contactos index large-9 medium-8 columns content">
    <h3><?= __('Contactos') ?></h3>
    <table cellpadding="0" cellspacing="0">
        <thead>
            <tr>
                <th scope="col"><?= $this->Paginator->sort('id') ?></th>
                <th scope="col"><?= $this->Paginator->sort('persona_id') ?></th>
                <th scope="col"><?= $this->Paginator->sort('movil') ?></th>
                <th scope="col"><?= $this->Paginator->sort('casa') ?></th>
                <th scope="col"><?= $this->Paginator->sort('twitter') ?></th>
                <th scope="col"><?= $this->Paginator->sort('facebook') ?></th>
                <th scope="col"><?= $this->Paginator->sort('email') ?></th>
                <th scope="col"><?= $this->Paginator->sort('created') ?></th>
                <th scope="col"><?= $this->Paginator->sort('modified') ?></th>
                <th scope="col" class="actions"><?= __('Actions') ?></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($contactos as $contacto): ?>
            <tr>
                <td><?= $this->Number->format($contacto->id) ?></td>
                <td><?= $this->Number->format($contacto->persona_id) ?></td>
                <td><?= h($contacto->movil) ?></td>
                <td><?= h($contacto->casa) ?></td>
                <td><?= h($contacto->twitter) ?></td>
                <td><?= h($contacto->facebook) ?></td>
                <td><?= h($contacto->email) ?></td>
                <td><?= h($contacto->created) ?></td>
                <td><?= h($contacto->modified) ?></td>
                <td class="actions">
                    <?= $this->Html->link(__('View'), ['action' => 'view', $contacto->id]) ?>
                    <?= $this->Html->link(__('Edit'), ['action' => 'edit', $contacto->id]) ?>
                    <?= $this->Form->postLink(__('Delete'), ['action' => 'delete', $contacto->id], ['confirm' => __('Are you sure you want to delete # {0}?', $contacto->id)]) ?>
                </td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    <div class="paginator">
        <ul class="pagination">
            <?= $this->Paginator->prev('< ' . __('previous')) ?>
            <?= $this->Paginator->numbers() ?>
            <?= $this->Paginator->next(__('next') . ' >') ?>
        </ul>
        <p><?= $this->Paginator->counter() ?></p>
    </div>
</div>

src/Template/Contactos/info.ctp
<?php $loguser = $this->request->session()->read('Auth.User'); ?>
<div class="col-md-10 col-md-offset-1 col-sm-12 fondo_blanco">
    <h3><?= __('Contactos') ?>
        <?php
        if($contactos->count()==0){
            echo $this->Html->link('Agregar',['controller' => 'contactos','action' => 'add',$loguser->persona->id],['class'=>'btn btn-success']);
        }else{
            echo $this->Html->link('Actualizar',['controller' => 'contactos','action' => 'edit',$contactos->toArray()[0]['id']],['class'=>'btn btn-warning']);
        }
        ?>
    </h3>
    <table cellpadding="0" cellspacing="0" class="table table-condensed table-striped table-responsive">
        <tbody>
            <?php foreach ($contactos as $contacto): ?>
            <tr>
                <th>
                    Telf. Móvil
                </th>
                <td><?= h($contacto->movil) ?></td>
                <tr>
                    <th>
                        Telf. Local
                    </th>
                    <td><?= h($contacto->casa) ?></td>
                </tr>
                <tr>
                    <th>
                        Twitter
                    </th>
                    <td>
                        <?php if($contacto->twitter){ ?>
                        <a href="https://twitter.com/<?= substr($contacto->twitter,1,1000) ?>" target="_blank"><?= h($contacto->twitter) ?></a>
                        <?php }else{ echo "No proporcionó.";} ?>
                    </td>
                </tr>
                <tr>
                    <th>
                        Facebook
                    </th>
                    <td>
                        <?php if($contacto->twitter){ ?>
                        <a href="https://www.facebook.com/<?= $contacto->facebook ?>" target="_blank"><?= h($contacto->facebook) ?></a>
                        <?php }else{ echo "No proporcionó.";} ?>
                    </td>
                </tr>
                <tr>
                    <th>
                        Correo Electrónico
                    </th>
                    <td><?= h($loguser->email) ?></td>
                </tr>
                <tr>
                    <td class="actions" colspan="2">
                        <?= $this->element('actions',['dato'=>$contacto])?>
                    </td>
                </tr>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>