config/routes.php
<?php
/**
 * Routes configuration
 *
 * In this file, you set up routes to your controllers and their actions.
 * Routes are very important mechanism that allows you to freely connect
 * different URLs to chosen controllers and their actions (functions).
 *
 * CakePHP(tm) : Rapid Development Framework (http://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)
 * @link          http://cakephp.org CakePHP(tm) Project
 * @license       http://www.opensource.org/licenses/mit-license.php MIT License
 */

use Cake\Core\Plugin;
use Cake\Routing\RouteBuilder;
use Cake\Routing\Router;
use Cake\Routing\Route\DashedRoute;

/**
 * The default class to use for all routes
 *
 * The following route classes are supplied with CakePHP and are appropriate
 * to set as the default:
 *
 * - Route
 * - InflectedRoute
 * - DashedRoute
 *
 * If no call is made to `Router::defaultRouteClass()`, the class used is
 * `Route` (`Cake\Routing\Route\Route`)
 *
 * Note that `Route` does not do any inflections on URLs which will result in
 * inconsistently cased URLs when used with `:plugin`, `:controller` and
 * `:action` markers.
 *
 */
Router::defaultRouteClass(DashedRoute::class);

Router::scope('/', function (RouteBuilder $routes) {
    /**
     * Here, we are connecting '/' (base path) to a controller called 'Pages',
     * its action called 'display', and we pass a param to select the view file
     * to use (in this case, src/Template/Pages/home.ctp)...
     */
    $routes->connect('/', ['controller' => 'users', 'action' => 'login']);

    /**
     * ...and connect the rest of 'Pages' controller's URLs.
     */
    $routes->connect('/pages/*', ['controller' => 'Pages', 'action' => 'display']);

    /**
     * Connect catchall routes for all controllers.
     *
     * Using the argument `DashedRoute`, the `fallbacks` method is a shortcut for
     *    `$routes->connect('/:controller', ['action' => 'index'], ['routeClass' => 'DashedRoute']);`
     *    `$routes->connect('/:controller/:action/*', [], ['routeClass' => 'DashedRoute']);`
     *
     * Any route class can be used with this method, such as:
     * - DashedRoute
     * - InflectedRoute
     * - Route
     * - Or your own route class
     *
     * You can remove these routes once you've connected the
     * routes you want in your application.
     */
    $routes->fallbacks(DashedRoute::class);
});

/**
 * Load all plugin routes.  See the Plugin documentation on
 * how to customize the loading of plugin routes.
 */
Plugin::routes();

src/Model/Entity/Parroquia.php
<?php
namespace App\Model\Entity;

use Cake\ORM\Entity;

/**
 * Parroquia Entity
 *
 * @property int $id
 * @property int $municipio_id
 * @property string $parroquia
 *
 * @property \App\Model\Entity\Municipio $municipio
 * @property \App\Model\Entity\Persona[] $personas
 */
class Parroquia extends Entity
{

    /**
     * Fields that can be mass assigned using newEntity() or patchEntity().
     *
     * Note that when '*' is set to true, this allows all unspecified fields to
     * be mass assigned. For security purposes, it is advised to set '*' to false
     * (or remove it), and explicitly make individual fields accessible as needed.
     *
     * @var array
     */
    protected $_accessible = [
        '*' => true,
        'id' => false
    ];
}

src/Model/Entity/User.php
<?php
namespace App\Model\Entity;

use Cake\Auth\DefaultPasswordHasher;
use Cake\ORM\Entity;

/**
 * User Entity
 *
 * @property int $id
 * @property string $email
 * @property string $password
 * @property \Cake\I18n\Time $access
 * @property \Cake\I18n\Time $created
 * @property \Cake\I18n\Time $modified
 *
 * @property \App\Model\Entity\Noticia[] $noticias
 * @property \App\Model\Entity\Persona[] $personas
 * @property \App\Model\Entity\Rol[] $rols
 */
class User extends Entity
{

    /**
     * Fields that can be mass assigned using newEntity() or patchEntity().
     *
     * Note that when '*' is set to true, this allows all unspecified fields to
     * be mass assigned. For security purposes, it is advised to set '*' to false
     * (or remove it), and explicitly make individual fields accessible as needed.
     *
     * @var array
     */
    protected $_accessible = [
        '*' => true,
        'id' => false
    ];

    /**
     * Fields that are excluded from JSON versions of the entity.
     *
     * @var array
     */
    protected $_hidden = [
        'password'
    ];
    protected function _setPassword($password)
    {
        if (strlen($password) > 0) {
            return (new DefaultPasswordHasher)->hash($password);
        }
    }

/*    protected function _getNacionalidad($n)
    {
        return $n==0?'Venezolano':'Extranjero';
    }

    protected function _getNacionalidadOpciones($n)
    {
        return ['Venezolano','Extranjero'];
    }
    protected function _getSexo($n)
    {
        return $n==0?'Masculino':'Femenino';
    }

    protected function _getSexoOpciones($n)
    {
        return ['Masculino','Femenino'];
    }*/
}

src/Model/Table/ParroquiasTable.php
<?php
namespace App\Model\Table;

use Cake\ORM\Query;
use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\Validation\Validator;

/**
 * Parroquias Model
 *
 * @property \Cake\ORM\Association\BelongsTo $Municipios
 * @property \Cake\ORM\Association\HasMany $Personas
 *
 * @method \App\Model\Entity\Parroquia get($primaryKey, $options = [])
 * @method \App\Model\Entity\Parroquia newEntity($data = null, array $options = [])
 * @method \App\Model\Entity\Parroquia[] newEntities(array $data, array $options = [])
 * @method \App\Model\Entity\Parroquia|bool save(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \App\Model\Entity\Parroquia patchEntity(\Cake\Datasource\EntityInterface $entity, array $data, array $options = [])
 * @method \App\Model\Entity\Parroquia[] patchEntities($entities, array $data, array $options = [])
 * @method \App\Model\Entity\Parroquia findOrCreate($search, callable $callback = null)
 */
class ParroquiasTable extends Table
{

    public function lista($id = null)
    {
        $this->viewBuilder()->layout('ajax');
        $parroquias = $this->getParroquias($id);
        $this->set('parroquias', $parroquias);
    }

    /**
     * Initialize method
     *
     * @param array $config The configuration for the Table.
     * @return void
     */
    public function initialize(array $config)
    {
        parent::initialize($config);

        $this->table('parroquias');
        $this->displayField('id');
        $this->primaryKey('id');

        $this->belongsTo('Municipios', [
            'foreignKey' => 'municipio_id',
            'joinType' => 'INNER'
        ]);
        $this->hasMany('Personas', [
            'foreignKey' => 'parroquia_id'
        ]);
    }

    /**
     * Default validation rules.
     *
     * @param \Cake\Validation\Validator $validator Validator instance.
     * @return \Cake\Validation\Validator
     */
    public function validationDefault(Validator $validator)
    {
        $validator
            ->integer('id')
            ->allowEmpty('id', 'create');

        $validator
            ->requirePresence('parroquia', 'create')
            ->notEmpty('parroquia');

        return $validator;
    }

    /**
     * Returns a rules checker object that will be used for validating
     * application integrity.
     *
     * @param \Cake\ORM\RulesChecker $rules The rules object to be modified.
     * @return \Cake\ORM\RulesChecker
     */
    public function buildRules(RulesChecker $rules)
    {
        $rules->add($rules->existsIn(['municipio_id'], 'Municipios'));

        return $rules;
    }
}

src/Controller/ParroquiasController.php
<?php
namespace App\Controller;

use App\Controller\AppController;
use Cake\Event\Event;
use Cake\ORM\TableRegistry;

/**
 * Parroquias Controller
 *
 * @property \App\Model\Table\ParroquiasTable $Parroquias
 */
class ParroquiasController extends AppController
{

    public function beforeFilter(Event $event)
    {
        parent::beforeFilter($event);
        //$this->Auth->allow(['registro', 'logout','login','index','add']);
        $this->Auth->allow();
    }

    /**
     * Index method
     *
     * @return \Cake\Network\Response|null
     */
    public function index()
    {
        $this->paginate = [
            'contain' => ['Municipios']
        ];
        $parroquias = $this->paginate($this->Parroquias);

        $this->set(compact('parroquias'));
        $this->set('_serialize', ['parroquias']);
    }

    public function lista($id = null)
    {
        $this->viewBuilder()->layout('ajax');
        $parroquias = $this->getParroquias($id);
        $this->set('parroquias', $parroquias);
    }

    /**
     * View method
     *
     * @param string|null $id Parroquia id.
     * @return \Cake\Network\Response|null
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function view($id = null)
    {
        $parroquia = $this->Parroquias->get($id, [
            'contain' => ['Municipios', 'Personas']
        ]);

        $this->set('parroquia', $parroquia);
        $this->set('_serialize', ['parroquia']);
    }

    /**
     * Add method
     *
     * @return \Cake\Network\Response|void Redirects on successful add, renders view otherwise.
     */
    public function add()
    {
        $parroquia = $this->Parroquias->newEntity();
        if ($this->request->is('post')) {
            $parroquia = $this->Parroquias->patchEntity($parroquia, $this->request->data);
            if ($this->Parroquias->save($parroquia)) {
                $this->Flash->success(__('The parroquia has been saved.'));

                return $this->redirect(['action' => 'index']);
            } else {
                $this->Flash->error(__('The parroquia could not be saved. Please, try again.'));
            }
        }
        $municipios = $this->Parroquias->Municipios->find('list', ['limit' => 200]);
        $this->set(compact('parroquia', 'municipios'));
        $this->set('_serialize', ['parroquia']);
    }

    /**
     * Edit method
     *
     * @param string|null $id Parroquia id.
     * @return \Cake\Network\Response|void Redirects on successful edit, renders view otherwise.
     * @throws \Cake\Network\Exception\NotFoundException When record not found.
     */
    public function edit($id = null)
    {
        $parroquia = $this->Parroquias->get($id, [
            'contain' => []
        ]);
        if ($this->request->is(['patch', 'post', 'put'])) {
            $parroquia = $this->Parroquias->patchEntity($parroquia, $this->request->data);
            if ($this->Parroquias->save($parroquia)) {
                $this->Flash->success(__('The parroquia has been saved.'));

                return $this->redirect(['action' => 'index']);
            } else {
                $this->Flash->error(__('The parroquia could not be saved. Please, try again.'));
            }
        }
        $municipios = $this->Parroquias->Municipios->find('list', ['limit' => 200]);
        $this->set(compact('parroquia', 'municipios'));
        $this->set('_serialize', ['parroquia']);
    }

    /**
     * Delete method
     *
     * @param string|null $id Parroquia id.
     * @return \Cake\Network\Response|null Redirects to index.
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function delete($id = null)
    {
        $this->request->allowMethod(['post', 'delete']);
        $parroquia = $this->Parroquias->get($id);
        if ($this->Parroquias->delete($parroquia)) {
            $this->Flash->success(__('The parroquia has been deleted.'));
        } else {
            $this->Flash->error(__('The parroquia could not be deleted. Please, try again.'));
        }

        return $this->redirect(['action' => 'index']);
    }
}

src/Template/Parroquias/add.ctp
<nav class="large-3 medium-4 columns" id="actions-sidebar">
    <ul class="side-nav">
        <li class="heading"><?= __('Actions') ?></li>
        <li><?= $this->Html->link(__('List Parroquias'), ['action' => 'index']) ?></li>
        <li><?= $this->Html->link(__('List Municipios'), ['controller' => 'Municipios', 'action' => 'index']) ?></li>
        <li><?= $this->Html->link(__('New Municipio'), ['controller' => 'Municipios', 'action' => 'add']) ?></li>
        <li><?= $this->Html->link(__('List Personas'), ['controller' => 'Personas', 'action' => 'index']) ?></li>
        <li><?= $this->Html->link(__('New Persona'), ['controller' => 'Personas', 'action' => 'add']) ?></li>
        <li><?= $this->Html->link(__('List Residencia'), ['controller' => 'Residencia', 'action' => 'index']) ?></li>
        <li><?= $this->Html->link(__('New Residencium'), ['controller' => 'Residencia', 'action' => 'add']) ?></li>
    </ul>
</nav>
<div class="parroquias form large-9 medium-8 columns content">
    <?= $this->Form->create($parroquia) ?>
    <fieldset>
        <legend><?= __('Add Parroquia') ?></legend>
        <?php
            echo $this->Form->input('municipio_id', ['options' => $municipios]);
            echo $this->Form->input('parroquia');
        ?>
    </fieldset>
    <?= $this->Form->button(__('Submit')) ?>
    <?= $this->Form->end() ?>
</div>

src/Template/Parroquias/edit.ctp
<nav class="large-3 medium-4 columns" id="actions-sidebar">
    <ul class="side-nav">
        <li class="heading"><?= __('Actions') ?></li>
        <li><?= $this->Form->postLink(
                __('Delete'),
                ['action' => 'delete', $parroquia->id],
                ['confirm' => __('Are you sure you want to delete # {0}?', $parroquia->id)]
            )
        ?></li>
        <li><?= $this->Html->link(__('List Parroquias'), ['action' => 'index']) ?></li>
        <li><?= $this->Html->link(__('List Municipios'), ['controller' => 'Municipios', 'action' => 'index']) ?></li>
        <li><?= $this->Html->link(__('New Municipio'), ['controller' => 'Municipios', 'action' => 'add']) ?></li>
        <li><?= $this->Html->link(__('List Personas'), ['controller' => 'Personas', 'action' => 'index']) ?></li>
        <li><?= $this->Html->link(__('New Persona'), ['controller' => 'Personas', 'action' => 'add']) ?></li>
        <li><?= $this->Html->link(__('List Residencia'), ['controller' => 'Residencia', 'action' => 'index']) ?></li>
        <li><?= $this->Html->link(__('New Residencium'), ['controller' => 'Residencia', 'action' => 'add']) ?></li>
    </ul>
</nav>
<div class="parroquias form large-9 medium-8 columns content">
    <?= $this->Form->create($parroquia) ?>
    <fieldset>
        <legend><?= __('Edit Parroquia') ?></legend>
        <?php
            echo $this->Form->input('municipio_id', ['options' => $municipios]);
            echo $this->Form->input('parroquia');
        ?>
    </fieldset>
    <?= $this->Form->button(__('Submit')) ?>
    <?= $this->Form->end() ?>
</div>

src/Template/Parroquias/index.ctp
<nav class="large-3 medium-4 columns" id="actions-sidebar">
    <ul class="side-nav">
        <li class="heading"><?= __('Actions') ?></li>
        <li><?= $this->Html->link(__('New Parroquia'), ['action' => 'add']) ?></li>
        <li><?= $this->Html->link(__('List Municipios'), ['controller' => 'Municipios', 'action' => 'index']) ?></li>
        <li><?= $this->Html->link(__('New Municipio'), ['controller' => 'Municipios', 'action' => 'add']) ?></li>
        <li><?= $this->Html->link(__('List Personas'), ['controller' => 'Personas', 'action' => 'index']) ?></li>
        <li><?= $this->Html->link(__('New Persona'), ['controller' => 'Personas', 'action' => 'add']) ?></li>
        <li><?= $this->Html->link(__('List Residencia'), ['controller' => 'Residencia', 'action' => 'index']) ?></li>
        <li><?= $this->Html->link(__('New Residencium'), ['controller' => 'Residencia', 'action' => 'add']) ?></li>
    </ul>
</nav>
<div class="parroquias index large-9 medium-8 columns content">
    <h3><?= __('Parroquias') ?></h3>
    <table cellpadding="0" cellspacing="0">
        <thead>
            <tr>
                <th><?= $this->Paginator->sort('id') ?></th>
                <th><?= $this->Paginator->sort('municipio_id') ?></th>
                <th><?= $this->Paginator->sort('parroquia') ?></th>
                <th class="actions"><?= __('Actions') ?></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($parroquias as $parroquia): ?>
            <tr>
                <td><?= $this->Number->format($parroquia->id) ?></td>
                <td><?= $parroquia->has('municipio') ? $this->Html->link($parroquia->municipio->id, ['controller' => 'Municipios', 'action' => 'view', $parroquia->municipio->id]) : '' ?></td>
                <td><?= h($parroquia->parroquia) ?></td>
                <td class="actions">
                    <?= $this->Html->link(__('View'), ['action' => 'view', $parroquia->id]) ?>
                    <?= $this->Html->link(__('Edit'), ['action' => 'edit', $parroquia->id]) ?>
                    <?= $this->Form->postLink(__('Delete'), ['action' => 'delete', $parroquia->id], ['confirm' => __('Are you sure you want to delete # {0}?', $parroquia->id)]) ?>
                </td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    <div class="paginator">
        <ul class="pagination">
            <?= $this->Paginator->prev('< ' . __('previous')) ?>
            <?= $this->Paginator->numbers() ?>
            <?= $this->Paginator->next(__('next') . ' >') ?>
        </ul>
        <p><?= $this->Paginator->counter() ?></p>
    </div>
</div>

src/Template/Parroquias/lista.ctp
<?php

echo $this->Form->input('parroquia_id', ['options' => $parroquias,'label'=>false,'div'=>false,'class'=>'form-control']);

 ?>

src/Template/Parroquias/view.ctp
<nav class="large-3 medium-4 columns" id="actions-sidebar">
    <ul class="side-nav">
        <li class="heading"><?= __('Actions') ?></li>
        <li><?= $this->Html->link(__('Edit Parroquia'), ['action' => 'edit', $parroquia->id]) ?> </li>
        <li><?= $this->Form->postLink(__('Delete Parroquia'), ['action' => 'delete', $parroquia->id], ['confirm' => __('Are you sure you want to delete # {0}?', $parroquia->id)]) ?> </li>
        <li><?= $this->Html->link(__('List Parroquias'), ['action' => 'index']) ?> </li>
        <li><?= $this->Html->link(__('New Parroquia'), ['action' => 'add']) ?> </li>
        <li><?= $this->Html->link(__('List Municipios'), ['controller' => 'Municipios', 'action' => 'index']) ?> </li>
        <li><?= $this->Html->link(__('New Municipio'), ['controller' => 'Municipios', 'action' => 'add']) ?> </li>
        <li><?= $this->Html->link(__('List Personas'), ['controller' => 'Personas', 'action' => 'index']) ?> </li>
        <li><?= $this->Html->link(__('New Persona'), ['controller' => 'Personas', 'action' => 'add']) ?> </li>
        <li><?= $this->Html->link(__('List Residencia'), ['controller' => 'Residencia', 'action' => 'index']) ?> </li>
        <li><?= $this->Html->link(__('New Residencium'), ['controller' => 'Residencia', 'action' => 'add']) ?> </li>
    </ul>
</nav>
<div class="parroquias view large-9 medium-8 columns content">
    <h3><?= h($parroquia->id) ?></h3>
    <table class="vertical-table">
        <tr>
            <th><?= __('Municipio') ?></th>
            <td><?= $parroquia->has('municipio') ? $this->Html->link($parroquia->municipio->id, ['controller' => 'Municipios', 'action' => 'view', $parroquia->municipio->id]) : '' ?></td>
        </tr>
        <tr>
            <th><?= __('Parroquia') ?></th>
            <td><?= h($parroquia->parroquia) ?></td>
        </tr>
        <tr>
            <th><?= __('Id') ?></th>
            <td><?= $this->Number->format($parroquia->id) ?></td>
        </tr>
    </table>
    <div class="related">
        <h4><?= __('Related Personas') ?></h4>
        <?php if (!empty($parroquia->personas)): ?>
        <table cellpadding="0" cellspacing="0">
            <tr>
                <th><?= __('Id') ?></th>
                <th><?= __('Nacionalidad') ?></th>
                <th><?= __('Cedula') ?></th>
                <th><?= __('Nombre') ?></th>
                <th><?= __('Nombre 1') ?></th>
                <th><?= __('Apellido') ?></th>
                <th><?= __('Apellido 1') ?></th>
                <th><?= __('Nacimiento') ?></th>
                <th><?= __('Estado Id') ?></th>
                <th><?= __('Municipio Id') ?></th>
                <th><?= __('Parroquia Id') ?></th>
                <th><?= __('Contacto Id') ?></th>
                <th><?= __('Usuario Id') ?></th>
                <th><?= __('Created') ?></th>
                <th><?= __('Modified') ?></th>
                <th class="actions"><?= __('Actions') ?></th>
            </tr>
            <?php foreach ($parroquia->personas as $personas): ?>
            <tr>
                <td><?= h($personas->id) ?></td>
                <td><?= h($personas->nacionalidad) ?></td>
                <td><?= h($personas->cedula) ?></td>
                <td><?= h($personas->nombre) ?></td>
                <td><?= h($personas->nombre_1) ?></td>
                <td><?= h($personas->apellido) ?></td>
                <td><?= h($personas->apellido_1) ?></td>
                <td><?= h($personas->nacimiento) ?></td>
                <td><?= h($personas->estado_id) ?></td>
                <td><?= h($personas->municipio_id) ?></td>
                <td><?= h($personas->parroquia_id) ?></td>
                <td><?= h($personas->contacto_id) ?></td>
                <td><?= h($personas->usuario_id) ?></td>
                <td><?= h($personas->created) ?></td>
                <td><?= h($personas->modified) ?></td>
                <td class="actions">
                    <?= $this->Html->link(__('View'), ['controller' => 'Personas', 'action' => 'view', $personas->id]) ?>
                    <?= $this->Html->link(__('Edit'), ['controller' => 'Personas', 'action' => 'edit', $personas->id]) ?>
                    <?= $this->Form->postLink(__('Delete'), ['controller' => 'Personas', 'action' => 'delete', $personas->id], ['confirm' => __('Are you sure you want to delete # {0}?', $personas->id)]) ?>
                </td>
            </tr>
            <?php endforeach; ?>
        </table>
        <?php endif; ?>
    </div>
    <div class="related">
        <h4><?= __('Related Residencia') ?></h4>
        <?php if (!empty($parroquia->residencia)): ?>
        <table cellpadding="0" cellspacing="0">
            <tr>
                <th><?= __('Id') ?></th>
                <th><?= __('Estado Id') ?></th>
                <th><?= __('Municipio Id') ?></th>
                <th><?= __('Parroquia Id') ?></th>
                <th><?= __('Ficha Id') ?></th>
                <th class="actions"><?= __('Actions') ?></th>
            </tr>
            <?php foreach ($parroquia->residencia as $residencia): ?>
            <tr>
                <td><?= h($residencia->id) ?></td>
                <td><?= h($residencia->estado_id) ?></td>
                <td><?= h($residencia->municipio_id) ?></td>
                <td><?= h($residencia->parroquia_id) ?></td>
                <td><?= h($residencia->ficha_id) ?></td>
                <td class="actions">
                    <?= $this->Html->link(__('View'), ['controller' => 'Residencia', 'action' => 'view', $residencia->id]) ?>
                    <?= $this->Html->link(__('Edit'), ['controller' => 'Residencia', 'action' => 'edit', $residencia->id]) ?>
                    <?= $this->Form->postLink(__('Delete'), ['controller' => 'Residencia', 'action' => 'delete', $residencia->id], ['confirm' => __('Are you sure you want to delete # {0}?', $residencia->id)]) ?>
                </td>
            </tr>
            <?php endforeach; ?>
        </table>
        <?php endif; ?>
    </div>
</div>